api_hash: "7dd9974c713787410beae4a295cc1e2d"
api_id: 27885485
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
- video_note
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
