api_hash: 7dd9974c713787410beae4a295cc1e2d
api_id: 27885485
chat_id: -1001899277831
last_read_message_id: 0
ids_to_retry: []
media_types:
- video
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
